name: SlimefunLuckyBlocks
version: ${project.version}
author: TheBusyBiscuit
website: https://github.com/TheBusyBiscuit/luckyblocks-sf/

api-version: 1.14
main: io.github.thebusybiscuit.slimefunluckyblocks.SlimefunLuckyBlocks

depend:
- Slimefun